spring:
  profiles: dev
  data:
    mongodb:
      username: ${MONGO_USER:mongo}
      password: ${MONGO_PASSWORD:mongo}
      host: ${MONGO_HOST:127.0.0.1}
      port: 27017
      database: ${MONGO_DB:admin}
serverfile:
  root: C:\Temp\plkserver
  base: C:\Temp\clientes
  model: C:\Temp\clientes\_base
  shutdown: C:\Temp\clientes\_desligados_extintas
obrigacaoconfig:
  obrigacoes:
    PROLINKDIGITAL: C:\Temp\Fiscal\PROLINK DIGITAL_FISCAL
    DCTF: C:\Temp\Fiscal\OBRIGAÇÕES FISCAIS\DCTF
    GIAICMS:	C:\Temp\Fiscal\OBRIGAÇÕES FISCAIS\GIA-ICMS
    REINF:	C:\Temp\Fiscal\OBRIGAÇÕES FISCAIS\REINF
    SEDIFDESTDA:	C:\Temp\Fiscal\OBRIGAÇÕES FISCAIS\SEDIF-DESTDA
    SIMPLESNACIONALPGDASD:	C:\Temp\Fiscal\OBRIGAÇÕES FISCAIS\SIMPLES NACIONAL-PGDASD
    SINTEGRA:	C:\Temp\Fiscal\OBRIGAÇÕES FISCAIS\SINTEGRA
    SPEDICMSIPI:	C:\Temp\Fiscal\OBRIGAÇÕES FISCAIS\SPED ICMS IPI
    SPEDPISCOFINS:	C:\Temp\Fiscal\OBRIGAÇÕES FISCAIS\SPED PIS COFINS
server:
  port: 8082
sqsurl:
  arquivo: ${SQS_ARQUIVO:https://sqs:us-east-1:amazonaws:com/707372836079/Arquivo-dev}
logging:
  config: classpath:logback-dev.xml
jwt:
  secret: ${FILE_SECRET:mytoken}
cloud:
  aws:
    credentials:
      accessKey: ${aws_access_key_id:access_key}
      secretKey: ${aws_secret_access_key:secret_key}
      instanceProfile: true
      useDefaultAwsCredentialsChain: true
    region:
      static: us-east-1
    stack:
      auto: false