spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: prolink
serverfile:
  root: C:\Temp\plkserver
  base: C:\Temp\clientes
  model: C:\Temp\clientes\_base
  shutdown: C:\Temp\clientes\_desligados_extintas
server:
  port: 8082