serverfile:
  base: /home/tiago/clientes
  model: /home/tiago/clientes/_base
  shutdown: /home/tiago/clientes/_desligados
server:
  port: 8082
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: prolink