serverfile:
  base: c:\clientes
  model: c:\clientes\_base
  shutdown: c:\clientes\_desligados_extintas
server:
  port: 8082
spring:
  data:
    mongodb:
      host: 192.168.43.187
      port: 27017
      database: prolink