version: '3'

services:
  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mongo
    - MONGO_INITDB_ROOT_PASSWORD=mongo
    - MONGO_INITDB_DATABASE=admin
    ports:
      - 27017:27017
    restart: always
    volumes:
      - db-data:/var/lib/mongo
volumes:
  db-data: